### ISSUE TITLE
Key Promoter X is not compatible to IDEA 2017.2

### ISSUE THREAD

**Issue by SLKun** [halirutan/IntelliJ-Key-Promoter#10] opened 2017-08-08 07:02 UTC
![qq 20170808145443](https://user-images.githubusercontent.com/10459559/29059997-877a2b0a-7c4a-11e7-88bb-d387e636beb9.png)
![qq 20170808145449](https://user-images.githubusercontent.com/10459559/29059998-877e905a-7c4a-11e7-8ea6-9db111f51579.png)

I hope this compatibility problem could be solved someday.

**Comment by hurricup** [comment] 2017-08-08 07:32
Would be nice to specify: 

1. Your JB product and version
2. Your OS
3. Your Key Promoter version.

Also, keep in mind that there are Key promoter and key promoter X. First one been updated 5 years ago and shouldn't be compatible. But current version of the X one works fine with 2017.2.1 release.

**Comment by halirutan** [comment] 2017-08-08 23:31
I can assure you that the *Key Promoter X* is compatible with the latest IDEA. First of all, the information about your system and the Key Promoter X plugin version you are using would be helpful. Other than that, your error seems to be the same another user had (https://github.com/halirutan/IntelliJ-Key-Promoter/issues/7) and I would like you to try the following steps:

1. Deinstall *Key Promoter X* **and** *Key Promoter* (if you have installed it)
2. Remove the statistics file by
    1. Go in IDEA to Help -> Show Log in File Manager. This gives you the log-folder. For me, it is under `/home/patrick/.IdeaIC2017.1/system/log/`
    2. Close IDEA
    3. Navigate to the equivalent folder on your machine `/home/patrick/.IdeaIC2017.1/config/options/` and delete the files that look like `KeyPromoterStatistic.xml`
    4. Restart IDEA
3. Reinstall the latest *Key Promoter X* version 5.7.2

**Comment by SLKun** [comment] 2017-08-09 01:41
Sorry for incomplete debug information.
My JB product and version is IDEA ultimate 2017.2.1.
My OS is Windows10(1703) v15063.483.
My Key Promter X version is v5.7.3.
And the solution by @halirutan works for me.
Thanks a lot. Perhaps it can be put into readme.md or somewhere else.

**Comment by halirutan** [comment] 2017-08-10 01:36
I'm not sure why you had this issue but new users should never experience this. The reason for this glitch is that I forgot to rename the `*xml` files where the KeyPromoterX stores the statistics for your shortcuts when I moved from the original KeyPromoter. What happened then is that the statistics file has an invalid format that cannot be read by KeyPromoterX.

**Comment by gregspeechley** [comment] 2017-08-12 04:53
On macOS Sierra (10.12.6) the file I had to delete was /Users/gregs/Library/Preferences/IntelliJIdea2017.2/options/KeyPromoterStats.xml

**Comment by halirutan** [comment] 2017-08-12 13:10
@gregspeechley @Summerslyb If this happens again, I really would like to inspect the `KeyPromoterXStatistic.xml` file that brings the error. I suspect that somehow there are `null` or wrong values inserted but I cannot reproduce it. It would be nice if you could put the file on pastebin.com when the error happens again.

**Comment by halirutan** [comment] 2017-08-13 01:19
Duplicate of

https://github.com/halirutan/IntelliJ-Key-Promoter-X/issues/5

Fix in the next version.

**Closed as completed by halirutan** 2017-08-13 01:19 UTC
